amaprt/installtointernal: refuse to run if device is not gxl_p212

diff --git a/projects/Amlogic-ce/packages/tools/ampart/installtointernal b/projects/Amlogic-ce/packages/tools/ampart/installtointernal
--- a/projects/Amlogic-ce/packages/tools/ampart/installtointernal
+++ b/projects/Amlogic-ce/packages/tools/ampart/installtointernal
@@ -200,6 +200,13 @@ install_to_nand() {
   fi
 }
 
+DT_NAME="$( /usr/bin/dtname )"
+if ! [[ "$DT_NAME" =~ ^gxl_p212 ]]; then
+  echo "ERROR: This script is only verified to work on gxl_p212 devices yet your device is $DT_NAME"
+  echo " - Please wait until Team EmuELEC can verify if it works for your device"
+  exit 1
+fi
+
 if [ ! -e /dev/env ]; then
   echo "ENV partition is missing."
   echo "Make sure that you are using a correct device tree and a device with internal memory!"
