ampart/installtointernal: ask for user whether to create EEROMS partition on emmc

diff --git a/projects/Amlogic-ce/packages/tools/ampart/installtointernal b/projects/Amlogic-ce/packages/tools/ampart/installtointernal
--- a/projects/Amlogic-ce/packages/tools/ampart/installtointernal
+++ b/projects/Amlogic-ce/packages/tools/ampart/installtointernal
@@ -7,26 +7,87 @@
 
 IMAGE_KERNEL="/flash/kernel.img"
 IMAGE_SYSTEM="/flash/SYSTEM"
-BACKUP_DATE=$(date +%Y%m%d%H%M%S)
 
 install_to_nand() {
   if [ -f $IMAGE_KERNEL -a -f $IMAGE_SYSTEM ] ; then
+    if grep -q '/dev/system /flash' /proc/mounts; then 
+      echo "ERROR: You are running EmuELEC from EMMC, can not install to EMMC."
+      echo "Reboot to a SD/USB installation and try again."
+      exit 1
+    fi
+    echo "Finding underlying block device for /dev/system..."
+    RDEV=''
+    for i in '/dev/block/'*; do
+      if [ "$(readlink -f $i)" == '/dev/system' ]; then
+        echo "Device major:minor pair for /dev/system is $i"
+        RDEV="$i"
+        break
+      fi
+    done
+    if [ -z "$RDEV" ]; then
+      echo "Failed to find underlying block device for /dev/system"
+      exit 1
+    fi
+    MAJOR="$(basename $RDEV | cut -d ':' -f 1)"
 
-    if grep -q /dev/system /proc/mounts ; then
-      echo "Unmounting SYSTEM partiton."
-      umount -f /dev/system
+
+    DISK_DEVICE=''
+    echo "Finding corresponding disk for it..."
+    for BLK_DEVICE in $(grep -e " *$MAJOR \+[0-9]\+ \+[0-9]\+ \+mmcblk" /proc/partitions); do
+      if [[ "$BLK_DEVICE" =~ ^mmcblk[0-9]$ ]]; then
+        DISK_DEVICE="$BLK_DEVICE"
+        echo "Found corresponding disk: $DISK_DEVICE"
+      fi
+    done
+    if [ -z "$DISK_DEVICE" ]; then
+      echo 'ERROR: Failed to find corresponding disk for /dev/system'
+      exit 1
     fi
 
-    if grep -q /dev/data /proc/mounts ; then
-      echo "Unmounting DATA partiton."
-      umount -f /dev/data
+    echo "Umounting all partitions under disk $DISK_DEVICE"
+    for i in "/dev/block/${MAJOR}:"*; do
+      PART="$(readlink -f $i)"
+      if grep -q "^$PART " /proc/mounts; then
+        echo "Umounting $PART..."
+        umount "$PART" || exit 1
+      fi
+    done
+
+    echo "All partitions under /dev/$DISK_DEVICE are not mounted, we can safely continue our work" 
+
+    DISK_SIZE=$(( $(cat "/sys/block/$DISK_DEVICE/size") * 512 ))
+    DISK_SIZE_INT=$(( $DISK_SIZE / 1073741824 + 1 ))
+    ROMS_CREATE=''
+
+    if [ "$DISK_SIZE" -gt 4294967296 ]; then
+      echo "Oh great! You emmc is larger than 4G (${DISK_SIZE_INT}G), so you can create a dedicated EEROMS partition to save your ROMs, savestates, etc"
+      read -p "Do you want to create a dedicated EEROMS partition? (if not, DATA partition will fill the rest of the disk) [Y/n] " choice
+      case "$choice" in
+        [yY]*)
+          TABLE='system::2G:2 data::2G: eeroms:::'
+          ROMS_CREATE='yes'
+          ;;
+        *)
+          TABLE='system::2G:2 data:::'
+          ;;
+      esac
+    elif [ "$DISK_SIZE" -gt 3221225472]; then
+      echo "Oops, You emmc is only 4G, to prevent DATA from filling up, you can not have a dedicated EEROMS partition :("
+      echo "Your new partition table on emmc will only contain a 2G system and a data partition to fill the rest free space"
+      TABLE='system::2G:2 data:::'
+    else
+      echo "Oh no! You emmc is smaller than 4G! This is impossible!"
+      echo "Every Amlogic S9xxx device should have at least 4G emmc onboard!"
+      echo "I'm afraid you can not install EmuELEC to internal storage :("
+      echo "As this only works on emmc at least 4G :<"
+      exit 1
     fi
 
     echo "Backing up env partition..."
     dd if=/dev/env of=/tmp/env.img &>/dev/null
 
     echo "Creating new partition table..."
-    ampart /dev/mmcblk0 system::2G:2 data::: &> /dev/null
+    ampart $DISK_DEVICE $TABLE &> /dev/null
     if [ ! $? ]; then
       echo "Failed to create new partition table, exiting..."
       exit
@@ -46,6 +107,9 @@ install_to_nand() {
     echo -n "Copying all system files (kernel, SYSTEM, dtb, etc) under EMUELEC partition to internal SYSTEM partition..."
     mount -o rw /dev/system /tmp/system
     cp -rva /flash/* /tmp/system && sync
+    if [ "$ROMS_CREATE" ]; then
+      echo 'ext4' > /tmp/system/ee_fstype   ## Internal EEROMS should always be EXT4
+    fi
     echo "done."
 
     umount /tmp/system
@@ -55,7 +119,11 @@ install_to_nand() {
     e2fsck -n /dev/data &> /dev/null
     echo "done."
 
-    read -p "Do you want to copy your user data to internal data partition? [Y/n] " choice
+    if [ "$ROMS_CREATE" ]; then
+      read -p "Do you want to copy your user data to internal data partition? (This will not include all of the stuffs under /storage/roms, they will be copied to EEROMS partition later) [Y/n] " choice
+    else
+      read -p "Do you want to copy your user data to internal data partition? [Y/n] " choice
+    fi
     case "$choice" in
       [nN]*)
         :
@@ -67,9 +135,39 @@ install_to_nand() {
         echo "Copying user data..."
         mkdir -p /tmp/data
         mount -o rw /dev/data /tmp/data
-        cp -pPRv /storage/. /tmp/data
+        rsync -qaHSx /storage/. /tmp/data
+        umount /tmp/data
+        sync
+        echo "done."
         ;;
     esac
+
+    if [ "$ROMS_CREATE" ]; then
+      ROMS_PART='/dev/eeroms'
+      echo -n "Formatting EEROMS partition..."
+      echo "Note: EEROMS on the emmc will always be formatted as EXT4"
+      echo " - Since you can not plug the emmc to a Windows PC just like"
+      echo " - you would for a SD card/USB drive"
+      mke2fs -F -q -t ext4 -m 0 /dev/eeroms -L EEROMS > /dev/null
+      e2fsck -n /dev/eeroms &> /dev/null
+      echo "done."
+      read -p "Do you want to copy all of your ROMs, savestates, etc under /storage/roms to internal EEROMS partition? [Y/n]" choice
+        case "$choice" in
+        [nN]*)
+          :
+          ;;
+        *)
+          echo "Copying Roms, savestates, etc..."
+          mkdir -p /tmp/eeroms
+          mount -o rw /dev/eeroms /tmp/eeroms
+          rsync -qaHSx /storage/roms/. /tmp/eeroms
+          umount /tmp/eeroms
+          sync
+          echo "done."
+          ;;
+      esac
+    fi
+
 
     echo "All done!"
     echo "Your system will reboot from internal memory."
@@ -99,7 +197,7 @@ if [ ! -e /dev/system -o ! -e /dev/data -o ! -e /dev/env ]; then
 fi
 
 echo "This script will erase the old partition table on your emmc"
-echo "and create a new part table that ONLY contains SYSTEM and DATA partiitons"
+echo "and create a new part table that ONLY contains SYSTEM, DATA and EEROMS partiitons"
 echo "(reserved partitions like bootloader, reserved and env will be kept)"
 echo "and install EmuELEC that you booted from SD card/USB drive."
 echo ""
