ampart/installtointernal: minor tweaks

diff --git a/projects/Amlogic-ce/packages/tools/ampart/installtointernal b/projects/Amlogic-ce/packages/tools/ampart/installtointernal
--- a/projects/Amlogic-ce/packages/tools/ampart/installtointernal
+++ b/projects/Amlogic-ce/packages/tools/ampart/installtointernal
@@ -25,6 +25,26 @@ die() {
   exit 1
 }
 
+PART_RESIZED=''
+PART_MOUNTED=''
+
+revert_and_die() {
+  printf "ERROR: "
+  echo $*
+  echo "Reverting changes..."
+  for i in $PART_MOUNTED; do
+    umount -f "$i"
+  fi
+  sync
+  ampart --clone $SNAPSHOT &>/dev/null
+  sync
+  if [ "$PART_RESIZED" ]; then
+    resize_part "$PART_RESIZED"
+  fi
+  sync
+  exit 1
+}
+
 snapshot() {
   local LOG="$(ampart --snapshot /dev/mmcblk0 2>/dev/null)" || die "Failed to read partition table"
   SNAPSHOT="$(sed 'x;$!d' <<< $LOG)" # We can restore the part table in case something goes wrong
@@ -60,14 +80,18 @@ resize_part() { # $1 part name $2 size in K, we use K as 1. resize2fs does not a
   elif [ $RTR != 0 ]; then
     die "Failed to fsck on partition /dev/$1, there's something wrong in the partition, you may need to fix it yourself"
   fi
-  resize2fs "/dev/$1" "$2K" || "Failed to resize partition /dev/$1, may be space is not enough?"
+  if [ "$2" ]; then
+    resize2fs "/dev/$1" "$2K" || "Failed to resize partition /dev/$1, may be space is not enough?"
+  else
+    resize2fs "/dev/$1" || "Failed to resize partition /dev/$1, may be space is not enough?"
+  fi
 }
 
-revert_table() {
-  ampart --clone $SNAPSHOT &>/dev/null
-  echo "Oops, failed to install EmuELEC to internal storage, but don't worry, everything we have done is reverted"
-  exit 1
-}
+# revert_table() {
+#   ampart --clone $SNAPSHOT &>/dev/null
+#   echo "Oops, failed to install EmuELEC to internal storage, but don't worry, everything we have done is reverted"
+#   exit 1
+# }
 
 update_table() {
   ROMS_CREATE=''
@@ -85,10 +109,10 @@ update_table() {
     PART_SIZE="$(awk -F ':' '{print $3}' <<< $PART)"
     echo "Shrinking partition $PART_NAME by 2G..."
     resize_part "$PART_NAME" $(( ($PART_SIZE - 0x80000000) / 1024 ))
+    PART_RESIZED="$PART_NAME"
     ampart --update /dev/mmcblk0 ^-1:::-2G: ^-1%:CE_STORAGE CE_FLASH::: &>/dev/null
     if [ $? != 0 ]; then
-      resize_part "$PART_NAME" $(( $PART_SIZE  / 1024 ))
-      revert_table
+      revert_and_die
     fi
   else
     # Single boot mode
@@ -119,7 +143,7 @@ update_table() {
       fi
     ampart /dev/mmcblk0 $TABLE &>/dev/null
     if [ $? != 0 ]; then
-      revert_table
+      revert_and_die
     fi
   fi
 }
@@ -154,15 +178,36 @@ create_ext4() { # $1: name
   e2fsck -fy "$1" &> /dev/null || die "Filesystem glitched on '$1', this should be impossible as we just created it. Maybe you have a bad emmc?"
 }
 
+notice_populate_start() {
+  echo "Populating internal $PART_NAME partition..."
+}
+notice_populate_end() {
+  echo "Populated internal $PART_NAME partition..."
+}
+notice_format() {
+  echo "Formatting internal $PART_NAME partition..."
+
+}
+
+mount_part_cache() {
+  mkdir -p "$DIR_CACHE" || revert_and_die "Failed to create temp dir for '$PART_NAME'"
+  PART_MOUNTED+=" $PART_PATH"
+  mount -o rw "$PART_PATH" "$DIR_CACHE" || revert_and_die "Failed to mount '$PART_PATH' on '$DIR_CACHE'"
+}
+
+umount_and_sync() {
+  umount "$PART_PATH" &>/dev/null
+  sync
+}
+
 populate_ce_flash() {
   local PART_NAME='CE_FLASH'
-  echo "Populating internal $PART_NAME partition..."
-  echo "Formatting internal $PART_NAME partition..."
+  notice_populate_start
+  notice_format
   local PART_PATH="/dev/$PART_NAME"
-  mkfs.fat -n "$PART_NAME" "$PART_PATH" &>/dev/null || die "Failed to create a fat fs on '$PART_PATH'"
+  mkfs.fat -n "$PART_NAME" "$PART_PATH" &>/dev/null || revert_and_die "Failed to create a fat fs on '$PART_PATH'"
   local DIR_CACHE="$DIR_CACHE/$PART_NAME"
-  mkdir -p "$DIR_CACHE" || die "Failed to create temp dir for '$PART_NAME'"
-  mount -o rw "$PART_PATH" "$DIR_CACHE" || die "Failed to mount '$PART_PATH' on '$DIR_CACHE'"
+  mount_part_cache
   echo "copying all system files (kernel, SYSTEM, dtb, etc) under EMUELEC partition to internal $PART_NAME partition..."
   cp -ra /flash/* "$DIR_CACHE" || die 'Failed to copy system files'
   [ "$ROMS_CREATE" ] && echo 'ext4' > "$DIR_CACHE/ee_fstype"  # Internal roms fs type should always be ext4
@@ -170,22 +215,20 @@ populate_ce_flash() {
   #   # in single boot mode, storage is not in subfolder
   #   sed -i 's_disk=FOLDER=/dev/eestorage_disk=/dev/eestorage_' "$DIR_CACHE/cfgload" || die 'Failed to edit cfgload (in single boot mode kernel cmdline [disk=] should be different), did you remove it in your external drive?'
   # fi
-  umount "$PART_PATH" &>/dev/null
-  sync
-  echo "Populated internal $PART_NAME partition..."
+  umount_and_sync
+  notice_populate_start
 }
 
 populate_ce_storage() {
   local PART_NAME='CE_STORAGE'
-  echo "Populating internal $PART_NAME partition"
+  notice_populate_start
   local PART_PATH="/dev/$PART_NAME"
   local DIR_CACHE="$DIR_CACHE/$PART_NAME"
   if [ "$SINGLE_BOOT" == 'yes' ]; then
-    echo "Formatting internal $PART_NAME partition..."
+    notice_format
     create_ext4 "$PART_NAME"
   fi
-  mkdir -p "$DIR_CACHE" || die "Failed to create temp dir for '$PART_NAME'"
-  mount -o rw "$PART_PATH" "$DIR_CACHE" || die "Failed to mount '$PART_PATH' on '$DIR_CACHE'"
+  mount_part_cache
   DIR_CACHE="$DIR_CACHE/coreelec_storage"
   mkdir -p "$DIR_CACHE"
   chmod 755 "$DIR_CACHE" # Just in case, if it's already be created by some random user?
@@ -204,17 +247,16 @@ populate_ce_storage() {
       sync
       ;;
   esac
-  umount "$PART_PATH" &>/dev/null # It may fail as we could've never mounted it
-  sync
-  echo "Populated internal $PART_NAME partition"
+  umount_and_sync
+  notice_populate_end
 }
 
 populate_eeroms() {
   [ -z "$ROMS_CREATE" ] && return
   local PART_NAME='EEROMS'
-  echo "Populating internal $PART_NAME partition"
+  notice_populate_start
   local PART_PATH="/dev/$PART_NAME"
-  echo "Formatting $PART_NAME partition..."
+  notice_format
   echo "Note: $PART_NAME on the emmc will always be formatted as EXT4, Since you can not plug the emmc to a Windows PC just like you would for a SD card/USB drive"
   create_ext4 "$PART_NAME"
   read -p "Do you want to copy all of your ROMs, savestates, etc under /storage/roms to internal eeroms partition? [Y/n]" choice
@@ -225,14 +267,12 @@ populate_eeroms() {
     *)
       local DIR_CACHE="$DIR_CACHE/$PART_NAME"
       echo "Copying Roms, savestates, etc..."
-      mkdir -p "$DIR_CACHE" || die "Failed to create temp dir for '$PART_NAME'"
-      mount -o rw "$PART_PATH" "$DIR_CACHE" || die "Failed to mount '$PART_PATH' on '$DIR_CACHE'"
+      mount_part_cache
       rsync -qaHSx /storage/roms/. "$DIR_CACHE"
-      umount "$PART_PATH" &>/dev/null
-      sync
+      umount_and_sync
       ;;
   esac
-  echo 'Populated internal eeroms partition'
+  notice_populate_end
 }
 
 finish_work() {
